[tool.poetry]
name = "weather"
version = "0.1.0"
description = ""
authors = ["Alex_K <Kagan.alex23@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
streamlit = "^1.41.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
